import { Recipe } from '@/types';

export const RECIPES_DATABASE: Recipe[] = [
  // ================= BREAKFAST =================
  {
    id: 'b1',
    name: 'Creamy Berry Rolled Oats Porridge',
    cuisine: 'American',
    mealType: 'Breakfast',
    cookingTime: 15,
    calories: 320,
    macros: { protein: 12, carbs: 54, fat: 6 },
    requiredIngredients: ['1 cup Rolled Oats', '2 cups Almond Milk', '1 tbsp Honey', '1/4 cup Mixed Berries'],
    baseIngredients: ['rolled oats', 'almond milk', 'berries'],
    instructions: [
      'Bring almond milk to a gentle boil in a small saucepan.',
      'Stir in the rolled oats and simmer on low heat for 5-7 minutes, stirring occasionally, until creamy.',
      'Pour into a bowl, drizzle with honey, and top with fresh mixed berries.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Weight Loss', 'Diabetic Friendly', 'Low Carb'],
    estimatedCostPerPortion: 1.5,
  },
  {
    id: 'b2',
    name: 'Classic Protein Scrambled Eggs',
    cuisine: 'American',
    mealType: 'Breakfast',
    cookingTime: 15,
    calories: 280,
    macros: { protein: 18, carbs: 12, fat: 16 },
    requiredIngredients: ['2 large Eggs', '2 slices Bread / Whole Wheat Toast', '1 tsp Butter / Olive Oil', 'Salt and Pepper to taste'],
    baseIngredients: ['eggs', 'bread / whole wheat toast', 'butter / olive oil'],
    instructions: [
      'Crack the eggs into a bowl, add a pinch of salt and pepper, and whisk thoroughly.',
      'Heat butter/olive oil in a non-stick skillet over medium-low heat.',
      'Pour in the eggs, letting them sit for a few seconds, then sweep gently with a spatula until soft curds form (about 2-3 minutes).',
      'Toast your bread slices, and serve the scrambled eggs hot on top.'
    ],
    dietTags: ['Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 1.2,
  },
  {
    id: 'b3',
    name: 'Spiced Tofu Scramble',
    cuisine: 'Asian',
    mealType: 'Breakfast',
    cookingTime: 15,
    calories: 240,
    macros: { protein: 16, carbs: 10, fat: 14 },
    requiredIngredients: ['150g Tofu', '1/2 cup Tomatoes (chopped)', '1/2 cup Onions (chopped)', '1/2 tsp Turmeric & Garlic Powder', '1 tbsp Butter / Olive Oil'],
    baseIngredients: ['tofu', 'tomatoes', 'onions', 'butter / olive oil'],
    instructions: [
      'Drain the tofu and crumble it with your hands or a fork.',
      'Heat olive oil in a pan, sauté onions and chopped tomatoes for 3 minutes.',
      'Add the crumbled tofu, turmeric, garlic powder, salt, and pepper.',
      'Cook for 5 minutes, stirring continuously, until heated through and golden. Serve warm.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Weight Loss', 'Diabetic Friendly', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 1.8,
  },
  {
    id: 'b4',
    name: 'Indian Style Masala Paneer Bhurji',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    cookingTime: 20,
    calories: 340,
    macros: { protein: 18, carbs: 14, fat: 22 },
    requiredIngredients: ['150g Paneer', '1/2 cup Onions (chopped)', '1/2 cup Tomatoes (chopped)', '1 tsp Ginger (grated)', '1 tsp Garlic (minced)', '1 tbsp Butter / Olive Oil', 'Spices (Turmeric, Garam Masala)'],
    baseIngredients: ['paneer', 'onions', 'tomatoes', 'ginger', 'garlic', 'butter / olive oil'],
    instructions: [
      'Crumble the paneer and set aside.',
      'Heat oil or butter in a pan. Sauté ginger, garlic, and chopped onions until translucent.',
      'Add chopped tomatoes and cook for 3-4 minutes until they turn soft.',
      'Add turmeric, garam masala, and salt. Stir in the crumbled paneer.',
      'Cook for 3-4 minutes on medium heat. Garnish with fresh herbs and serve hot.'
    ],
    dietTags: ['Veg', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 2.2,
  },
  {
    id: 'b5',
    name: 'Avocado Spinach Toast',
    cuisine: 'Mediterranean',
    mealType: 'Breakfast',
    cookingTime: 15,
    calories: 290,
    macros: { protein: 8, carbs: 32, fat: 15 },
    requiredIngredients: ['1/2 Avocado', '1 cup Spinach', '2 slices Bread / Whole Wheat Toast', '1 tsp Lemon juice', '1 tbsp Butter / Olive Oil'],
    baseIngredients: ['avocado', 'spinach', 'bread / whole wheat toast', 'butter / olive oil', 'lemon'],
    instructions: [
      'In a small bowl, mash the avocado with lemon juice, salt, and pepper.',
      'Sauté the spinach in a pan with a drop of olive oil for 2 minutes until wilted.',
      'Toast the bread slices.',
      'Spread the mashed avocado onto the toast, top with sautéed spinach, and enjoy.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Weight Loss', 'Diabetic Friendly', 'Low Carb'],
    estimatedCostPerPortion: 2.5,
  },

  // ================= LUNCH =================
  {
    id: 'l1',
    name: 'Mediterranean Chickpea & Avocado Salad',
    cuisine: 'Mediterranean',
    mealType: 'Lunch',
    cookingTime: 15,
    calories: 420,
    macros: { protein: 12, carbs: 45, fat: 18 },
    requiredIngredients: ['1 cup Lentils / Beans (boiled chickpeas)', '1/2 Avocado (cubed)', '1/2 cup Tomatoes (chopped)', '1/2 cup Cucumber (chopped)', '1 tbsp Olive Oil', '1 tbsp Lemon juice'],
    baseIngredients: ['lentils / beans', 'avocado', 'tomatoes', 'lemon'],
    instructions: [
      'Rinse and drain boiled chickpeas (or canned chickpeas).',
      'In a large salad bowl, combine the chickpeas, cubed avocado, chopped tomatoes, and cucumber.',
      'Drizzle with olive oil, freshly squeezed lemon juice, salt, and pepper.',
      'Toss gently and serve chilled or at room temperature.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Weight Loss', 'Diabetic Friendly', 'Low Carb'],
    estimatedCostPerPortion: 2.0,
  },
  {
    id: 'l2',
    name: 'Grilled Herb Chicken with Broccoli',
    cuisine: 'American',
    mealType: 'Lunch',
    cookingTime: 30,
    calories: 450,
    macros: { protein: 38, carbs: 15, fat: 12 },
    requiredIngredients: ['150g Chicken breast', '1.5 cups Broccoli florets', '1 tbsp Olive Oil', '1 tsp Garlic (minced)', '1 tsp Lemon juice', 'Spices (Thyme, Rosemary)'],
    baseIngredients: ['chicken', 'broccoli', 'butter / olive oil', 'garlic', 'lemon'],
    instructions: [
      'Marinate chicken breast with lemon juice, minced garlic, herbs, salt, and half the olive oil.',
      'Heat a grill pan or skillet over medium-high heat and cook the chicken for 6-8 minutes on each side until fully cooked through.',
      'Steam or sauté the broccoli florets in the remaining oil with a splash of water for 4-5 minutes until tender-crisp.',
      'Slice the chicken and serve alongside the broccoli.'
    ],
    dietTags: ['Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 3.5,
  },
  {
    id: 'l3',
    name: 'Home-style Dal Tadka with Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    cookingTime: 30,
    calories: 490,
    macros: { protein: 16, carbs: 78, fat: 8 },
    requiredIngredients: ['1/2 cup Lentils / Beans (Yellow Dal)', '1 cup Rice (Basmati/Brown)', '1/2 cup Onions (chopped)', '1/2 cup Tomatoes (chopped)', '1 tbsp Butter / Olive Oil', '1 tsp Ginger-Garlic paste', 'Spices (Cumin seeds, Turmeric, Chili)'],
    baseIngredients: ['lentils / beans', 'rice (basmati/brown)', 'onions', 'tomatoes', 'ginger', 'garlic', 'butter / olive oil'],
    instructions: [
      'Rinse and pressure cook or boil lentils in water with turmeric and salt until mushy.',
      'Cook the rice in a separate pot (1:2 ratio of rice to water).',
      'In a small pan, heat butter/oil. Sauté cumin seeds, ginger-garlic paste, and onions until brown.',
      'Add chopped tomatoes and dry spices. Cook until oil separates.',
      'Pour this tempering (tadka) over the boiled lentils, mix well, and simmer for 3 minutes. Serve hot with rice.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Diabetic Friendly'],
    estimatedCostPerPortion: 1.0,
  },
  {
    id: 'l4',
    name: 'Classic Spaghetti Aglio e Olio',
    cuisine: 'Italian',
    mealType: 'Lunch',
    cookingTime: 20,
    calories: 460,
    macros: { protein: 10, carbs: 68, fat: 16 },
    requiredIngredients: ['100g Pasta / Spaghetti', '3-4 cloves Garlic (sliced)', '2 tbsp Butter / Olive Oil', '1/2 tsp Red pepper flakes', 'Fresh parsley (chopped)'],
    baseIngredients: ['pasta / spaghetti', 'garlic', 'butter / olive oil'],
    instructions: [
      'Cook pasta in a pot of boiling salted water according to package instructions until al dente.',
      'Reserve 1/4 cup of pasta water, then drain the spaghetti.',
      'In a large skillet, heat olive oil over medium-low heat. Add sliced garlic and red pepper flakes. Cook slowly until garlic is golden (do not burn).',
      'Toss the drained pasta and reserved pasta water into the skillet. Toss well to create a glossy sauce.',
      'Garnish with chopped fresh parsley and serve immediately.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet'],
    estimatedCostPerPortion: 1.2,
  },
  {
    id: 'l5',
    name: 'High-Protein Egg Fried Rice',
    cuisine: 'Asian',
    mealType: 'Lunch',
    cookingTime: 20,
    calories: 480,
    macros: { protein: 20, carbs: 62, fat: 14 },
    requiredIngredients: ['2 large Eggs', '1.5 cups Rice (Basmati/Brown) (cooked & cold)', '1/2 cup Carrots & Green Beans (diced)', '1/2 cup Onions (chopped)', '1 tbsp Garlic (minced)', '1.5 tbsp Butter / Olive Oil', 'Soy Sauce to taste'],
    baseIngredients: ['eggs', 'rice (basmati/brown)', 'carrots', 'onions', 'garlic', 'butter / olive oil'],
    instructions: [
      'Heat 1/2 tbsp of oil in a wok or large skillet and scramble the eggs. Remove and set aside.',
      'Heat the remaining oil. Sauté onions, garlic, diced carrots, and green beans for 4-5 minutes until tender.',
      'Add the cold cooked rice, breaking up any clumps, and toss with the vegetables on high heat.',
      'Drizzle with soy sauce and stir in the scrambled eggs. Stir-fry for 2-3 minutes. Serve hot.'
    ],
    dietTags: ['Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein'],
    estimatedCostPerPortion: 1.4,
  },
  {
    id: 'l6',
    name: 'Paneer Tikka Quinoa Salad',
    cuisine: 'Indian',
    mealType: 'Lunch',
    cookingTime: 25,
    calories: 430,
    macros: { protein: 22, carbs: 38, fat: 20 },
    requiredIngredients: ['120g Paneer (cubed)', '1/2 cup Quinoa (dry)', '1/2 cup Bell Peppers (cubed)', '1/2 cup Onions (cubed)', '1 tbsp Greek Yogurt', '1 tbsp Butter / Olive Oil', 'Spices (Tikka Masala, Chili)'],
    baseIngredients: ['paneer', 'quinoa', 'bell peppers', 'onions', 'greek yogurt', 'butter / olive oil'],
    instructions: [
      'Rinse quinoa, cook in 1 cup of water for 15 minutes, and fluff with a fork.',
      'Marinate paneer cubes, onions, and bell peppers in Greek yogurt mixed with tikka spices and salt.',
      'Heat oil in a grill pan or skillet. Cook the marinated paneer and vegetables for 6-8 minutes until charred.',
      'Toss the grilled tikka items with the cooked quinoa in a bowl. Serve warm or cold.'
    ],
    dietTags: ['Veg', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 2.8,
  },

  // ================= DINNER =================
  {
    id: 'd1',
    name: 'Garlic Butter Chicken Breast with Spinach',
    cuisine: 'American',
    mealType: 'Dinner',
    cookingTime: 25,
    calories: 460,
    macros: { protein: 42, carbs: 8, fat: 24 },
    requiredIngredients: ['180g Chicken breast', '2 cups Spinach', '2 tbsp Butter / Olive Oil', '1 tbsp Garlic (minced)', '1 tsp Lemon juice', 'Salt & Pepper to taste'],
    baseIngredients: ['chicken', 'spinach', 'butter / olive oil', 'garlic', 'lemon'],
    instructions: [
      'Season chicken breast with salt and pepper.',
      'In a skillet, melt butter/olive oil over medium-high heat. Sear the chicken for 6-7 minutes on each side until golden and cooked.',
      'Push the chicken to one side, add minced garlic and sauté for 30 seconds until fragrant.',
      'Throw in the spinach and cook until wilted (about 2 minutes). Drizzle with lemon juice and serve.'
    ],
    dietTags: ['Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Low Carb'],
    estimatedCostPerPortion: 3.8,
  },
  {
    id: 'd2',
    name: 'Tofu & Vegetable Stir Fry with Basmati Rice',
    cuisine: 'Asian',
    mealType: 'Dinner',
    cookingTime: 25,
    calories: 410,
    macros: { protein: 18, carbs: 54, fat: 12 },
    requiredIngredients: ['150g Tofu (cubed)', '1 cup Broccoli florets', '1/2 cup Carrots (sliced)', '1 cup Rice (Basmati/Brown) (cooked)', '1 tbsp Soy Sauce & Ginger (grated)', '1 tbsp Butter / Olive Oil'],
    baseIngredients: ['tofu', 'broccoli', 'carrots', 'rice (basmati/brown)', 'butter / olive oil', 'ginger'],
    instructions: [
      'Press the tofu to remove excess water, then cut into cubes.',
      'Heat oil in a large skillet. Pan-fry tofu cubes until golden on all sides, then remove.',
      'In the same skillet, add sliced ginger, broccoli, and carrots. Stir-fry for 5 minutes with a splash of water.',
      'Return tofu to the pan, toss with soy sauce, and cook for 2 minutes.',
      'Serve warm over a bed of freshly steamed Basmati rice.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Weight Loss', 'Diabetic Friendly', 'Balanced Diet', 'Low Carb'],
    estimatedCostPerPortion: 2.1,
  },
  {
    id: 'd3',
    name: 'Palak Paneer with Brown Rice',
    cuisine: 'Indian',
    mealType: 'Dinner',
    cookingTime: 30,
    calories: 490,
    macros: { protein: 22, carbs: 48, fat: 20 },
    requiredIngredients: ['120g Paneer (cubed)', '3 cups Spinach (pureed)', '1 cup Rice (Basmati/Brown) (cooked)', '1/2 cup Onions (chopped)', '1 tsp Ginger-Garlic paste', '1 tbsp Butter / Olive Oil', 'Spices (Cumin, Garam Masala)'],
    baseIngredients: ['paneer', 'spinach', 'rice (basmati/brown)', 'onions', 'ginger', 'garlic', 'butter / olive oil'],
    instructions: [
      'Blanch the spinach in hot water for 2 minutes, shock in cold water, and blend into a smooth puree.',
      'Sauté cubed paneer in a pan with a little oil until light brown. Set aside.',
      'Heat oil/butter in the same pan. Sauté cumin seeds, ginger-garlic paste, and onions until translucent.',
      'Add spices, pour in the spinach puree, and let it simmer for 5 minutes.',
      'Gently fold in the paneer cubes. Simmer for another 2 minutes and serve warm with brown rice.'
    ],
    dietTags: ['Veg', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Muscle Gain', 'High Protein', 'Diabetic Friendly'],
    estimatedCostPerPortion: 2.6,
  },
  {
    id: 'd4',
    name: 'Quick Pasta Primavera',
    cuisine: 'Italian',
    mealType: 'Dinner',
    cookingTime: 25,
    calories: 450,
    macros: { protein: 12, carbs: 64, fat: 14 },
    requiredIngredients: ['100g Pasta / Spaghetti', '1/2 cup Broccoli', '1/2 cup Bell Peppers', '1/2 cup Tomatoes (chopped)', '1 tbsp Olive Oil', 'Garlic (minced)', 'Cheese (Cheddar/Parmesan) to garnish'],
    baseIngredients: ['pasta / spaghetti', 'broccoli', 'bell peppers', 'tomatoes', 'butter / olive oil', 'garlic', 'cheese (cheddar/parmesan)'],
    instructions: [
      'Cook pasta in salted water. Drain and set aside.',
      'Sauté minced garlic, broccoli, and sliced bell peppers in olive oil for 4 minutes.',
      'Add chopped tomatoes and cook for 3 minutes until soft.',
      'Toss pasta with the vegetables, drizzle with olive oil, and serve topped with cheese.'
    ],
    dietTags: ['Veg', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet'],
    estimatedCostPerPortion: 1.8,
  },
  {
    id: 'd5',
    name: 'Mediterranean Shakshuka with Toast',
    cuisine: 'Mediterranean',
    mealType: 'Dinner',
    cookingTime: 25,
    calories: 380,
    macros: { protein: 16, carbs: 32, fat: 18 },
    requiredIngredients: ['2 large Eggs', '1.5 cups Tomatoes (crushed/chopped)', '1/2 cup Onions (chopped)', '1/2 cup Bell Peppers (chopped)', '2 slices Bread / Whole Wheat Toast', '1 tbsp Butter / Olive Oil', 'Spices (Paprika, Cumin, Garlic)'],
    baseIngredients: ['eggs', 'tomatoes', 'onions', 'bell peppers', 'bread / whole wheat toast', 'butter / olive oil'],
    instructions: [
      'Heat oil in a pan. Sauté chopped onions and bell peppers for 5 minutes until soft.',
      'Stir in crushed tomatoes and spices. Simmer for 10 minutes until sauce thickens.',
      'Crack the eggs directly into the tomato sauce, spacing them out.',
      'Cover the pan and cook on low heat for 5-8 minutes until egg whites are set but yolks are runny.',
      'Serve hot in the pan with warm toasted bread slices.'
    ],
    dietTags: ['Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Weight Loss', 'Diabetic Friendly', 'Low Carb'],
    estimatedCostPerPortion: 1.5,
  },
  {
    id: 'd6',
    name: 'Comforting Lentil & Vegetable Soup',
    cuisine: 'Mediterranean',
    mealType: 'Dinner',
    cookingTime: 30,
    calories: 330,
    macros: { protein: 18, carbs: 48, fat: 6 },
    requiredIngredients: ['1/2 cup Lentils / Beans (dry lentils)', '1 cup Carrots (chopped)', '1 cup Spinach', '1/2 cup Onions (chopped)', '2 cloves Garlic (minced)', '2 slices Bread / Whole Wheat Toast', '1 tbsp Butter / Olive Oil'],
    baseIngredients: ['lentils / beans', 'carrots', 'spinach', 'onions', 'garlic', 'bread / whole wheat toast', 'butter / olive oil'],
    instructions: [
      'Heat oil in a pot. Sauté onions and minced garlic for 2 minutes.',
      'Add chopped carrots, lentils, and 4 cups of water or vegetable broth. Bring to a boil.',
      'Reduce heat, cover, and simmer for 20-25 minutes until lentils and carrots are soft.',
      'Stir in the spinach and cook for 2 minutes until wilted. Season with salt and pepper.',
      'Serve warm in a bowl accompanied by toasted bread.'
    ],
    dietTags: ['Veg', 'Vegan', 'Eggetarian', 'Non-Veg'],
    healthGoals: ['Balanced Diet', 'Weight Loss', 'Diabetic Friendly', 'Low Carb'],
    estimatedCostPerPortion: 0.9,
  }
];
